### ISSUE TITLE
test/stdlib: Pass the runtime test

### ISSUE THREAD

**Issue by hajimehoshi** [hajimehoshi/go2cpp#9]
```
./run.sh runtime -test.v -test.short -test.run=^Test
```

Without `-test.short`, the tests take too long.

**Comment by hajimehoshi** [comment]
```
=== RUN   TestProfBuf/DataWraparound                                                                                                                                                                                                       
fatal error: unreachable                                                                                                                                                                                                                   
                                                                                                                                                                                                                                           
goroutine 19 [running]:                                                                                                                                                                                                                    
runtime.throw(0x8da77, 0xb)                                                                                                                                                                                                                
        runtime/panic.go:1114 +0x7 fp=0x4237f0 sp=0x4237c8 pc=0x12190007                                                                                                                                                                   
runtime.chanrecv(0x0, 0x423928, 0x1, 0x0)                                                                                                                                                                                                  
        runtime/chan.go:435 +0x7b fp=0x423878 sp=0x4237f0 pc=0x1067007b                                                                                                                                                                    
runtime.chanrecv1(0x0, 0x423928)                                                                                                                                                                                                           
        runtime/chan.go:407 +0x2 fp=0x4238a0 sp=0x423878 pc=0x10650002                                                                                                                                                                     
runtime: unexpected return pc for syscall.fsCall called from 0x0                                                                                                                                                                           
stack: frame={sp:0x4238a0, fp:0x423950} stack=[0x423000,0x423800)                                                                                                                                                                          
00000000004237a0:  0000000014040000 <runtime.fatalthrow.func1+0>  0000000000400d80                                                                                                                                                         
00000000004237b0:  0000000012190007 <runtime.throw+7>  00000000004237c8                                                                                                                                                                    
00000000004237c0:  0000000012190007 <runtime.throw+7>  00000000004237d0                                                                                                                                                                    
00000000004237d0:  0000000014030000 <runtime.throw.func1+0>  000000000008da77                                                                                                                                                              
00000000004237e0:  000000000000000b  000000001067007b <runtime.chanrecv+123>                                                                                                                                                               
00000000004237f0:  000000000008da77  000000000000000b                                                                                                                                                                                      
syscall.fsCall(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)                                                                                                                                                                                
        syscall/fs_js.go:515 +0xd fp=0x423950 sp=0x4238a0 pc=0x17b9000d                                                                                                                                                                    
created by runtime.beforeIdle                                                                                                                                                                                                              
        runtime/lock_js.go:184 +0x12
```

**Comment by hajimehoshi** [comment]
This seems flaky and might be #2

**Comment by hajimehoshi** [comment]
```
=== RUN   TestFakeTime
=== PAUSE TestFakeTime
=== CONT  TestCheckPtr
    TestCheckPtr: testenv.go:78: skipping test: 'go run' not available on js/wasm
--- SKIP: TestCheckPtr (0.00s)
=== CONT  TestFakeTime
apply on null is forbidden
Assertion failed: (false), function error, file autogen/js.cpp, line 17.
Abort trap: 6
```
